# Generated by Django 3.2.21 on 2023-10-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='owner',
        ),
    ]
