# Generated by Django 4.2.5 on 2023-10-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0002_alter_template_custom_id_alter_user_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='custom_id',
            field=models.CharField(default='3f3e5b06-e408-4d17-8a47-3ee9b29a4caa', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(default='da3a3a38-fb4d-49a6-a762-eda6215dfce1', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='custom_id',
            field=models.CharField(default='0d0b39d2-1cb5-4847-8a50-2a17e98e3f25', editable=False, max_length=36, unique=True),
        ),
    ]
