# Generated by Django 4.2.5 on 2023-10-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0003_alter_template_custom_id_alter_user_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='custom_id',
            field=models.CharField(default='1a9d38d1-9e8e-494a-ae53-331fcc09000c', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(default='c5e6be9d-6025-4633-81c6-3b4d4081c1ea', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='custom_id',
            field=models.CharField(default='d96bb8b0-17c8-44b7-a245-abd6edd7fb09', editable=False, max_length=36, unique=True),
        ),
    ]
