# Generated by Django 4.2.5 on 2023-10-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0004_alter_template_custom_id_alter_user_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='custom_id',
            field=models.CharField(default='c4c84cc4-6eac-476d-a444-c869c137ed96', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(default='e42e9705-b3e8-406e-8e0d-e9a7ac4efb2c', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='custom_id',
            field=models.CharField(default='f1a882ba-ee5b-4154-bbbd-f6d7125356cd', editable=False, max_length=36, unique=True),
        ),
    ]
