# Generated by Django 4.2.5 on 2023-10-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0006_alter_template_custom_id_alter_user_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='custom_id',
            field=models.CharField(default='6bec2394-2bc9-4b6b-8288-826fd53ce545', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(default='5fec07a1-bd40-4dbb-8fe4-4b2541056984', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='custom_id',
            field=models.CharField(default='6439cae0-fdea-410b-abab-7590350811d4', editable=False, max_length=36, unique=True),
        ),
    ]
