# Generated by Django 4.2.5 on 2023-10-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0007_alter_template_custom_id_alter_user_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='templat_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='custom_id',
            field=models.CharField(default='a592aeb9-9eb7-424b-a9a4-d2a3de79639c', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(default='986ed30e-1c6e-435a-ba9d-894c0a46814c', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='custom_id',
            field=models.CharField(default='c764e686-b1b8-4ef1-8b8f-1e4ce8d05f61', editable=False, max_length=36, unique=True),
        ),
    ]
