# Generated by Django 4.2.5 on 2023-10-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0009_alter_template_custom_id_alter_user_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='custom_id',
            field=models.CharField(default='101b8891-ab46-4ccc-b51f-03c0ef8fbf96', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(default='b43aca61-03b6-4fdc-ae34-4c59418c83a7', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='custom_id',
            field=models.CharField(default='85c057cf-6898-435b-b85c-0f5b4299b769', editable=False, max_length=36, unique=True),
        ),
    ]
