# Generated by Django 4.2.5 on 2023-10-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0010_alter_template_custom_id_alter_user_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='custom_id',
            field=models.CharField(default='4ae5057e-81de-4834-8c2f-455c2e9c76a1', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(default='106f97db-d2df-467b-9ee7-0bb61aa974ab', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='custom_id',
            field=models.CharField(default='086ac723-3257-469e-b46e-c2f87e21608d', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='templat_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
