# Generated by Django 4.2.5 on 2023-10-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0011_alter_template_custom_id_alter_user_custom_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='custom_id',
        ),
    ]
