# Generated by Django 3.2.21 on 2023-10-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0013_auto_20231029_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdiApp.user'),
        ),
    ]
