# Generated by Django 3.2.21 on 2023-10-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdiApp', '0004_alter_template_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='custom_id',
            field=models.CharField(default='c8704f4a-1d72-4e22-b2aa-144e8bf7797d', editable=False, max_length=36, unique=True),
        ),
    ]
